### ISSUE TITLE
Slydepay Should Have Configurable/Dynamic Callback URL in PayLIVE

### ISSUE THREAD

**Issue by fadugyamfi** [DreamOval/slydepay-php-connector#6]
When making payments, we should be able to dynamically specify the Return/Callback URL instead of having it hard coded in the PayLIVE configuration.

This makes it difficult to test payments with different systems. 

This is not specifically a PHP connector issue, but it would need a property to be included in the connector to override the return/callback URL

**Comment by silentworks** [comment]
@fadugyamfi do you have an example of testing payments with different systems? I thought the purpose of this library was to only work with Slydepay.

**Comment by kdjomeda** [comment]
Hello Guys,
I think I understand this requirement and we have something like that just that it's not actively advertised because we believe there should be another elegant way of doing it. So this could be changed in future

So basically instead of doing the simple redirect to the paylive url you could post it there and in the post body pass a new callback url
```html
                    <div class="col-md-6 col-sm-6 col-xs-12">
                        <div class="x_panel">
                            <div class="x_content">
                                    <form action="<?php echo $config['payment']['api_post_redirect_url']; ?>"" method="post">
                                            <tr>
                                            <td width="130px"><label class=""> Ready for Payment ?</label>
                                                <input type="hidden" name="pay_token" value="<?php echo $responsePayload->result->payToken; ?>"/>
                                                <input type="hidden" name="call_back" value="<?php echo $config['payment']['callback_url']; ?>"/>
                                            </td>
                                            <td colspan="1"><button class="btn btn-info" type="reset">Cancel</button></td>
                                            <td colspan="2"><button class="btn btn-success" type="submit">Pay</button></td>
                                        </tr>

                                    </form>
                            </div>
                        </div>
```
you have  following parameters

- pay_token
- call_back

api_post_redirect is the paylive url that you are used do when calling the `header(location)` method of php the snippet above will display something like this image below

![dynamic callback form](https://cloud.githubusercontent.com/assets/407284/26402112/75bfa254-4078-11e7-8006-b418519aabfe.png)

When pay is clicked , the posts details to slydepay and when payment is complete Slydepay uses the content of the call_back param to do callback with.  This should get you going but remember this is just a n initial approach to provide a solution for whoever needs it. There will a more elegant implementation of this.

**Comment by silentworks** [comment]
@kdjomeda so is this something that is independent of the library? I can't see how the library obstructs this at the moment, so is it that @fadugyamfi wants a way to do this within the library itself?

Btw I don't remember seeing anything about this in the documentation, I normally say, if its not documented, it doesn't exist.

**Comment by kdjomeda** [comment]
@silentworks this is not encapsulated and was rolled out for a particular need. So it's **not documented at all** because of the nature of it. This doesn't really need to be in a library because of the nature of the post form. @fadugyamfi is free to give it a try if that is a crucial need.

**Comment by fadugyamfi** [comment]
Wow,. Very sorry I missed this discussion. I get too many GitHub notifications so missed this convo completely.

I believe @kdjomeda's info is what I was looking for. Basically, a way to tell Slydepay where to redirect to after payment, instead of it always redirecting to the call back URL on the PAYLIVE dashboard.

I'll test this functionality out soon, and hopefully it will help me make payments with Slydepay in more flexible on memberz.org

Cc: @silentworks

**Comment by kdjomeda** [comment]
kindly test and let us know
